artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/GuruChandra/DataSet/raw/refs/heads/main/creditcard.csv.zip
  local_data_file: artifacts/data_ingestion/creditcard.csv.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["creditcard.csv"]